version: '3.8'

services:

  backend:
    build: ./
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - dev-secrets.rc
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/sentences_db
    depends_on:
      - db

  frontend:
    build: ./chima-app
    restart: always
    volumes:
      - ./chima-app:/app
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
 