version: '3.8'

services:
  backend:
    build: ./path_to_flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py  # your flask entry file
      FLASK_RUN_HOST: 0.0.0.0
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:password@db:5432/sentences_db
    depends_on:
      - db

  frontend:
    build: ./path_to_react_app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentences_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
